//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.08.09 at 09:28:45 PM CST
//

package com.xdc.basic.tools.statemachine.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}context"/>
 *         &lt;element ref="{}states"/>
 *         &lt;element ref="{}events"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "context", "states", "events" })
@XmlRootElement(name = "root")
public class Root
{
    @XmlElement(required = true)
    protected String context;
    @XmlElement(required = true)
    protected States states;
    @XmlElement(required = true)
    protected Events events;

    /**
     * Gets the value of the context property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getContext()
    {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setContext(String value)
    {
        this.context = value;
    }

    /**
     * Gets the value of the states property.
     * 
     * @return
     *         possible object is
     *         {@link States }
     * 
     */
    public States getStates()
    {
        return states;
    }

    /**
     * Sets the value of the states property.
     * 
     * @param value
     *            allowed object is
     *            {@link States }
     * 
     */
    public void setStates(States value)
    {
        this.states = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *         possible object is
     *         {@link Events }
     * 
     */
    public Events getEvents()
    {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *            allowed object is
     *            {@link Events }
     * 
     */
    public void setEvents(Events value)
    {
        this.events = value;
    }
}
