package com.xdc.basic.example.mybatis.model;

public class Student
{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.id
	 * 
	 * @mbggenerated
	 */
	private Integer	id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.name
	 * 
	 * @mbggenerated
	 */
	private String	name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.gender
	 * 
	 * @mbggenerated
	 */
	private String	gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.major
	 * 
	 * @mbggenerated
	 */
	private String	major;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column student.grade
	 * 
	 * @mbggenerated
	 */
	private String	grade;

	public Student()
	{
		super();
	}

	public Student(Integer id, String name, String gender, String major, String grade)
	{
		super();
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.major = major;
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.id
	 * 
	 * @return the value of student.id
	 * 
	 * @mbggenerated
	 */
	public Integer getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.id
	 * 
	 * @param id
	 *            the value for student.id
	 * 
	 * @mbggenerated
	 */
	public void setId(Integer id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.name
	 * 
	 * @return the value of student.name
	 * 
	 * @mbggenerated
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.name
	 * 
	 * @param name
	 *            the value for student.name
	 * 
	 * @mbggenerated
	 */
	public void setName(String name)
	{
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.gender
	 * 
	 * @return the value of student.gender
	 * 
	 * @mbggenerated
	 */
	public String getGender()
	{
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.gender
	 * 
	 * @param gender
	 *            the value for student.gender
	 * 
	 * @mbggenerated
	 */
	public void setGender(String gender)
	{
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.major
	 * 
	 * @return the value of student.major
	 * 
	 * @mbggenerated
	 */
	public String getMajor()
	{
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.major
	 * 
	 * @param major
	 *            the value for student.major
	 * 
	 * @mbggenerated
	 */
	public void setMajor(String major)
	{
		this.major = major == null ? null : major.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column student.grade
	 * 
	 * @return the value of student.grade
	 * 
	 * @mbggenerated
	 */
	public String getGrade()
	{
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column student.grade
	 * 
	 * @param grade
	 *            the value for student.grade
	 * 
	 * @mbggenerated
	 */
	public void setGrade(String grade)
	{
		this.grade = grade == null ? null : grade.trim();
	}

	@Override
	public String toString()
	{
		return "Student [id=" + id + ", name=" + name + ", gender=" + gender + ", major=" + major + ", grade=" + grade
		        + "]";
	}

}